stages:
- test

drltt-code-check-job:
  stage: test
  script:
    - export BLACK_ARGS=" --check "
    - export CLANG_FORMAT_ARGS=" --dry-run "
    - ./format-code.sh
  interruptible: true

drltt-python-test-job:
  stage: test
  script:
    - ./test/test-python.sh
  artifacts:
    paths:
    - "test-log/"
    expire_in: 1 week
  interruptible: true

drltt-cpp-test-job:
  stage: test
  script:
    - ./cicd/test-cpp-ci.sh
  artifacts:
    paths:
    - "test-log/"
    expire_in: 1 week
  interruptible: true
  timeout: "10h 00m"

drltt-doc-test-job:
  stage: test
  script:
    - ./test/test-doc.sh
  artifacts:
    paths:
    - "test-log/"
    - "docs/build/"
    expire_in: 1 week
  interruptible: true

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_UPDATE_FLAGS: --jobs 4
  GIT_DEPTH: 1
  GIT_SUBMODULE_DEPTH: 1
  GET_SOURCES_ATTEMPTS: 10
