# Overriding config file for FAST TEST.
#   Can be used during debugging of tests.
#   Quicker than preparation with FORMAL TEST config  while ensuring enough consistency of testing results.

environment:
  tracking_length_lb: 45
  tracking_length_ub: 55

algorithm:
  learning_starts: 4096
  batch_size: 4096
  learning_rate: 1.0e-4
  tau: 0.001

learning:
    total_timesteps: 16384
    log_interval: 10

evaluation:
  eval_config:
    n_episodes: 20
