version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  apt_packages:
  - "protobuf-compiler=3.12.4-1ubuntu7.22.04.1"


python:
  install:
    - requirements: requirements/pypi.txt
    - requirements: requirements/pypi-doc.txt

sphinx:
  configuration: docs/source/conf.py
