version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  apt_packages:
  - "cmake"
  - "protobuf-compiler"
  - "doxygen"
  jobs:
    pre_build:
      - bash ./setup.sh


python:
  install:
    - requirements: requirements/pypi.txt
    - requirements: requirements/pypi-doc.txt

sphinx:
  configuration: docs/source/conf.py
